# SPDX-FileCopyrightText: 2025-2026 EDF (Electricité De France)
# SPDX-License-Identifier: LGPL-3.0-or-later
# Author : Yann Allioux

"""
Pipeline Context for Automated TAM (AutoTAM).

This module defines the central state holder for the AutoTAM pipeline. 
It carries data splits, tracking metadata, and inferred physical parameters 
across all mathematical stages (Parsing, Profiling, Engineering, and Expansion) 
to ensure a unified state without passing excessive arguments between classes.
"""

#: <context_imports>
import pandas as pd
import re
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional, Tuple
#: </context_imports>

#: <context_class>
@dataclass
class PipelineContext:
    """
    Central state holder for the AutoTAM pipeline.
    Carries data splits, metadata, and physical tracking parameters across all stages.
    """
    # 1. Macro-Splits (Chronological continuity for plotting and final evaluation)
    df_fit: Optional[pd.DataFrame] = None
    df_dev: Optional[pd.DataFrame] = None
    df_val: Optional[pd.DataFrame] = None
    historical_tail: Optional[pd.DataFrame] = None
    df_all_aug: Optional[pd.DataFrame] = None

    # 2. Evaluation & Scoring Configuration
    validation_strategy: str = 'auto'
    optimization_metric: str = 'rmse'
    complexity_penalty: float = 1.0  
    cv_folds: List[Tuple[pd.DataFrame, pd.DataFrame]] = field(default_factory=list)

    # 3. Metadata & Configuration
    formula_config: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
    target: str = ""
    date_col: Optional[str] = None
    group_col: Optional[str] = None
    lags: List[int] = field(default_factory=list)

    # 4. Search Space
    search_space: Dict[str, Any] = field(default_factory=dict)

    # 5. Physics & Horizon Inference (Populated dynamically during Expansion)
    steps_per_period: int = 1
    adaptive_lags: List[int] = field(default_factory=list)
    inferred_horizon: int = 1
    candidate_windows: List[int] = field(default_factory=list)

#: <context_complexity_methods>
    def estimate_complexity(self, formula: str) -> int:
        """
        Estimates the exact structural degrees of freedom (columns in the Primal matrix) 
        generated by a formula to accurately penalize complexity.
        """
        if not isinstance(formula, str) or "~" not in formula: 
            return 1
            
        rhs = formula.split("~")[1].strip()

        def parse_term_complexity(term_str: str) -> int:
            term_str = term_str.strip()
            if not term_str: return 0
            
            # 1. Tensor Products (Geometric Kronecker Multiplier)
            if term_str.startswith('te('):
                inner = term_str[3:-1]
                sub_terms = []
                depth = 0
                current = []
                for char in inner:
                    if char == '(': depth += 1
                    elif char == ')': depth -= 1
                    
                    if char == ',' and depth == 0:
                        sub_terms.append("".join(current).strip())
                        current = []
                    else:
                        current.append(char)
                if current: sub_terms.append("".join(current).strip())
                
                k_te = 1
                for sub in sub_terms:
                    k_te *= max(1, parse_term_complexity(sub))
                return k_te

            k = 1
            if term_str.startswith('c('):
                m = re.search(r'n_cat=(\d+)', term_str)
                k = max(1, int(m.group(1)) - 1) if m else 1
                
            elif term_str.startswith('s('):
                m_k = re.search(r'k=(\d+)', term_str)
                m_deg = re.search(r'deg=(\d+)', term_str)
                knots = int(m_k.group(1)) if m_k else 10
                deg = int(m_deg.group(1)) if m_deg else 3
                k = knots + deg  # Spline reality
                
            elif term_str.startswith('f('):
                m = re.search(r'k=(\d+)', term_str)
                harmonics = int(m.group(1)) if m else 10
                k = harmonics * 2  # Sine and Cosine for each harmonic
                                
            elif term_str.startswith('p('):
                m = re.search(r'deg=(\d+)', term_str)
                k = int(m.group(1)) if m else 3
                
            elif term_str.startswith('rbf('):
                m = re.search(r'n_centers=(\d+)', term_str)
                k = int(m.group(1)) if m else 10
                
            elif term_str.startswith('t('):
                t_m = re.search(r'n_trees=(\d+)', term_str)
                d_m = re.search(r'max_depth=(\d+)', term_str)
                trees = int(t_m.group(1)) if t_m else 10
                depth = int(d_m.group(1)) if d_m else 2
                k = trees * (2**depth)
                
            elif term_str.startswith('w('):
                s_m = re.search(r'n_scales=(\d+)', term_str)
                l_m = re.search(r'n_locations=(\d+)', term_str)
                scales = int(s_m.group(1)) if s_m else 3
                locs = int(l_m.group(1)) if l_m else 10
                k = scales * locs
                
            elif term_str.startswith('n('):
                n_m = re.search(r'n_neurons=(\d+)', term_str)
                l_m = re.search(r'n_hidden_layers=(\d+)', term_str)
                neurons = int(n_m.group(1)) if n_m else 10
                layers = int(l_m.group(1)) if l_m else 1
                # Heavy structural penalty for deep randomized architectures
                k = neurons * layers * 5 
                
            return max(1, k)

        # Safely split the RHS by top-level '+' to preserve nested components
        top_terms = []
        depth = 0
        current = []
        for char in rhs:
            if char == '(': depth += 1
            elif char == ')': depth -= 1
            
            if char == '+' and depth == 0:
                top_terms.append("".join(current).strip())
                current = []
            else:
                current.append(char)
        if current: 
            top_terms.append("".join(current).strip())

        total_k = sum(parse_term_complexity(t) for t in top_terms)
        return max(1, total_k)

    def penalize_score(self, score: float, formula: str, n_samples: int) -> float:
        """Applies an Information Criterion penalty to mitigate overfitting."""
        if score == float('inf') or n_samples <= 0: return float('inf')
        k = self.estimate_complexity(formula)
        return score * (1.0 + self.complexity_penalty * (k / max(1, n_samples)))
#: </context_complexity_methods>
#: </context_class>